# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gregory Ovenden - Wildlife Sound Recordist
email: gregoryovenden@gmail.com

description: Gregory Ovenden - Wildlife Sound Recordist, Location, Post Production and Studio Sound Engineer
baseurl: / # the subpath of your site, e.g. /blog
url: "http://www.thesoundfarmer.com" # the base hostname & protocol for your site, e.g. http://example.com

# template things
tag_line: Wildlife Sound Recordist, Location, Post Production and Studio Sound Engineer
twitter_username: thesoundfarmer

google_analytics: UA-91800172-1

permalink: :title

paginate: 5
paginate_path: "/blog/page/:num"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate

